FROM python:3.6

# Set environment variables
ENV PYTHONUNBUFFERED 1

# Set work directory.
RUN mkdir /workspace
WORKDIR /workspace

COPY ./PetsApi/requirements.txt /workspace/

# Install dependencies.
RUN pip install -r requirements.txt
