FROM python:3.6

# Set environment variables
ENV PYTHONUNBUFFERED 1

COPY ./PetsApi/requirements.txt /workspace/

# Install dependencies.
RUN pip install -r requirements.txt

# Set work directory.
RUN mkdir /workspace
WORKDIR /workspace