version: '3'

services:
  api:
    container_name: api
    build:
      dockerfile: ./docker/API/dockerfile
    volumes:
      - ../PetsApi:/api
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
  ui:
    container_name: ui
    build:
      dockerfile: ./docker/UI/dockerfile
    volumes: 
      - ../PetsAppUI:/ui
    ports:
      - "4200:4200"    
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"