# Generated by Django 3.2.7 on 2021-09-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('IsAgeAproximated', models.BooleanField()),
            ],
        ),
    ]
