# Generated by Django 3.2.7 on 2021-09-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='age',
            new_name='birthDate',
        ),
    ]
