# Generated by Django 3.2.7 on 2021-09-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetsApp', '0002_rename_age_pet_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
